version: "1"
projects:
  hyperforge:
    path: ../hyperforge
    branch: feat/lforge2-redesign
    main: true
  hub-core:
    path: ../hub-core
  hub-macro:
    path: ../hub-macro
  hub-transport:
    path: ../hub-transport
